name: "credstash"
description: "A suite of common tools for aws usage"
inputs:
  version:
    description: "The version of credstash"
    required: false
runs:
  using: "composite"
  steps:
    - name: install
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            python3-dev \
            python3-setuptools

          if [ -z "${{ inputs.version }}" ]; then
            sudo python3 -m pip install credstash
          else
            sudo python3 -m pip install credstash==${{ inputs.version }}
          fi

        elif [ "$RUNNER_OS" == "macOS" ]; then
          if [ -z "${{ inputs.version }}" ]; then
            brew install credstash
          else
            brew install credstash@${{ inputs.version }}
          fi
         
        else
            echo "$RUNNER_OS not supported"
            exit 1
        fi
      shell: bash
