name: "credstash"
description: "A suite of common tools for aws usage"
runs:
  using: "composite"
  steps:
    - name: install
      run: |
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
        python3 -m pip install --upgrade pip credstash
        python3 -m pip show credstash
        export PATH=$PATH:$HOME/.local/bin
      shell: bash
