name: "credstash"
description: "A suite of common tools for aws usage"
runs:
  using: "composite"
  steps:
    - name: install
      run: |
        sudo apt-get install -y build-essential libssl-dev libffi-dev python-dev
        pip3 install --upgrade pip credstash
      shell: bash
